apiVersion: apps/v1
kind: Deployment
metadata:
  name: chay-techs-frontend
  namespace: chay-techs-test
  labels:
    app: chay-techs-frontend
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chay-techs-frontend
  template:
    metadata:
      labels:
        app: chay-techs-frontend
        environment: production
    spec:
      containers:
        - name: chay-techs-frontend
          image: harbor.chay-techs.com/portfolio/portfolio-front:fakeDevelop_0b86a86
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: chay-techs-registry-key
